### ISSUE TITLE
quarantine opinions 

### ISSUE THREAD

**Issue by qunabu** [qunabu/covid-simulation#20]
- [x] preset that creates a wall on the stage 
- [x] some balls do not move

**Comment by qunabu** [comment]
![image](https://user-images.githubusercontent.com/214608/77304355-9bcdd780-6cf4-11ea-84be-d604e541e918.png)

**Comment by qunabu** [comment]
https://www.washingtonpost.com/graphics/2020/world/corona-simulator/ plus te różne opcje

**Comment by Rafal-Malko** [comment]
moje sugestie
1. wykres mógłby mieć skalę
2. opcja procentowa kwarantanny jednostek
3. kobiety maja niższą śmiertelność (dane z Chin) https://www.worldometers.info/coronavirus/coronavirus-age-sex-demographics/
